----------------------------------------------------------------- SEQUENCES
CREATE SEQUENCE AUT.SPM_SEC_CUENTA INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE AUT.SPM_SEC_TRANSACCION INCREMENT BY 1 START WITH 1;

---------------------------------------------------------------- TABLES
CREATE TABLE AUT.SPM_CUENTA
(
   ID_CUENTA   NUMBER NOT NULL,
   TITULAR VARCHAR2(100),
   SALDO NUMBER,
   NUMERO_CUENTA VARCHAR2(10),
   MONEDA VARCHAR2(50),
   ESTADO VARCHAR2(20),
   RETIRO_MONTO_SUPERIOR VARCHAR2(2),
   PRIMARY KEY (ID_CUENTA)
);

CREATE TABLE AUT.SPM_TRANSACCION
(
   ID_TRANSACCION     NUMBER NOT NULL,
   FECHA         DATE,
   TIPO_TRANSACCION   VARCHAR2(100),
   MONTO NUMBER,
   MONEDA   VARCHAR2(50),
   ID_CUENTA NUMBER,
   PRIMARY KEY (ID_TRANSACCION)
);

---------------------------------------------------------------- CONSTRAINTS

ALTER TABLE AUT.SPM_TRANSACCION ADD CONSTRAINT FK_SPM_TRANS_ID_CUENTA FOREIGN KEY (ID_CUENTA) REFERENCES AUT.SPM_CUENTA (ID_CUENTA);


---------------------------------------------------------------- GRANTS SEQUENCES 
GRANT SELECT ON AUT.SPM_SEC_CUENTA TO AUT;

GRANT SELECT ON AUT.SPM_SEC_TRANSACCION TO AUT;

---------------------------------------------------------------- GRANTS TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON AUT.SPM_CUENTA TO AUT;

GRANT SELECT, INSERT, UPDATE, DELETE ON AUT.SPM_TRANSACCION TO AUT;

